import { useState, useEffect, useRef } from "react";

const DRILLS = [
  { id:"reset", emoji:"🔄", title:"The Reset Button", tag:"FOCUS", color:"#00FF87", desc:"Clear your mind fast after losing a point", steps:["Breathe in 4 seconds, hold it","Breathe out 4 seconds, say 'next point'","Tap your racket edge — feel its weight","Walk to baseline, eyes forward"] },
  { id:"pressure", emoji:"🔥", title:"Pressure = Fuel", tag:"PRE-MATCH", color:"#FF6B35", desc:"Turn nerves into energy", steps:["Feel your heart — your body is ready","Say: 'I am ready'","Squeeze fist 3 seconds, release","Picture the ball hitting the sweet spot"] },
  { id:"focus", emoji:"🎯", title:"Ball. Just the Ball.", tag:"FOCUS", color:"#60A5FA", desc:"Train your eyes to track the ball", steps:["Close your eyes 5 seconds","Open and pick one spot to stare at","Imagine a yellow ball bouncing up","Use your eyes to 'catch' it"] },
  { id:"talk", emoji:"💬", title:"Coach Yourself", tag:"MENTAL TOUGHNESS", color:"#C084FC", desc:"Talk to yourself like a great coach", steps:["What would your coach say right now?","Switch criticism to instruction: 'move feet faster'","Say one encouraging thing, then nod","You are your own best teammate"] },
  { id:"breath", emoji:"🌊", title:"Tennis Breathing", tag:"PRE-MATCH", color:"#34D399", desc:"30-second calm-down before you serve", steps:["Walk slowly to the service line","Bounce ball 3x — exhale each time","Look at the service box, trace its shape","Think only about this point"] },
  { id:"win", emoji:"🏆", title:"Victory Replay", tag:"MENTAL TOUGHNESS", color:"#FBBF24", desc:"3-minute mental rehearsal before court", steps:["Picture your forehand landing perfectly","Feel the hit vibrate up your arm","Hear the ball bounce, opponent can't reach","Open eyes — carry that feeling onto court"] },
];
const TIPS = ["Lost the last point? Clean slate. Reset, breathe, go.","Nervous? Good. That energy means you care. Use it.","Feet are your engine. When mind blanks, move feet.","Talk like a coach, not a critic. 'Move faster' beats 'I'm bad'.","One point at a time. Only the next ball matters.","Same routine after bad shots. Your brain needs safety.","Best players aren't fearless. They just keep going.","Between points is where matches are won. Walk tall.","Tight? Bounce on your toes. Movement breaks tension.","Your opponent can't see inside your head. Stay confident."];
const CHALLENGES = [
  {id:"c0",text:"Use the Reset Button 3+ times after losing a point",points:30},
  {id:"c1",text:"Do Tennis Breathing before warming up",points:20},
  {id:"c2",text:"Only say encouraging things to yourself all practice",points:40},
  {id:"c3",text:"Tell a teammate one genuine compliment",points:25},
  {id:"c4",text:"Write down 1 thing you did well after practice",points:20},
];
const TOOLS = [
  {icon:"⏱️",label:"Focus Timer",desc:"Get in zone 10 min before match",detail:"Start the countdown. No phone, no distractions — just you, your breathing, and how you feel."},
  {icon:"💪",label:"Power Phrase",desc:"Find your personal battle cry",detail:"Find a phrase only yours. 'I am ready', 'Move your feet', or anything that makes you feel powerful."},
  {icon:"🧘",label:"Body Scan",desc:"Relax shoulders and jaw",detail:"Head to toe: Is your forehead relaxed? Shoulders? Hands? Soften each one."},
  {icon:"🗺️",label:"Tactic Check",desc:"Run through your game plan",detail:"How will you serve? Opponent's strongest shot? How will you respond? Be ready."},
];
const GUIDED = {
  match:["What went well in this match?","What was your biggest mental challenge?","What will you do differently next time?"],
  practice:["What did you work on today?","When did you feel most focused?","What's one thing to improve tomorrow?"],
  mental:["How is your confidence right now?","One negative thought to let go?","Your mental goal for next session?"],
};
const STYLES=["Aggressive Baseliner","Counterpuncher","All-Court Player","Serve-and-Volley","Clay-Court Grinder","First-Strike Attacker"];
const WEAPONS=["Big Server","Heavy Forehand","Elite Mover","Return Specialist","Net/Rally Specialist","Timing Player","Heavy Spin","Flat Hitter"];
const PHYSICAL=["Explosive Athlete","Endurance Grinder","Power Player","Quick-Twitch Anticipator","Flexible Mover"];
const MENTAL_T=["Front-Runner","Clutch Competitor","Emotional Momentum","Tactical Thinker","Relentless Competitor"];
const HANDS=["Right-Handed","Left-Handed"];
const BH=["Two-Handed BH","One-Handed BH","Two-Handed FH","Two-Handed Both"];

function Ring({value,max,color,size=60}){
  const r=(size-8)/2,c=2*Math.PI*
export default function App(){
  const [tab,setTab]=useState("home");
  const [activeDrill,setActiveDrill]=useState(null);
  const [doneD,setDoneD]=useState([]);
  const [doneCh,setDoneCh]=useState([]);
  const [pts,setPts]=useState(0);
  const [dHistory,setDHistory]=useState([]);
  const [pmStep,setPmStep]=useState(null);
  const [tip,setTip]=useState(()=>Math.floor(Math.random()*TIPS.length));
  const RG=800,RP=50;
  const [ropeTotal,setRopeTotal]=useState(0),[ropeIn,setRopeIn]=useState(""),[ropeSess,setRopeSess]=useState([]),[ropeDone,setRopeDone]=useState(0),[showRope,setShowRope]=useState(false);
  const addRope=()=>{const n=parseInt(ropeIn);if(!n||n<=0)return;const nt=ropeTotal+n,e=Math.floor(nt/RG)-Math.floor(ropeTotal/RG);setRopeTotal(nt);setRopeSess(s=>[{n,date:new Date().toLocaleDateString("en-US",{month:"short",day:"numeric"}),time:new Date().toLocaleTimeString("en-US",{hour:"2-digit",minute:"2-digit"})},...s].slice(0,20));setRopeIn("");if(e>0){setRopeDone(c=>c+e);setPts(p=>p+e*RP);setShowRope(true);setTimeout(()=>setShowRope(false),3000);}};
  const [strCnt,setStrCnt]=useState(0),[strOn,setStrOn]=useState(false),[strS,setStrS]=useState(300),[strLog,setStrLog]=useState([]),[showStr,setShowStr]=useState(false);
  const strRef=useRef();
  useEffect(()=>{
    if(strOn&&strS>0){strRef.current=setInterval(()=>setStrS(s=>s-1),1000);}
    else if(strS===0){clearInterval(strRef.current);setStrOn(false);setStrCnt(c=>c+1);setStrLog(l=>[{date:new Date().toLocaleDateString("en-US",{month:"short",day:"numeric"}),time:new Date().toLocaleTimeString("en-US",{hour:"2-digit",minute:"2-digit"})},...l].slice(0,20));setPts(p=>p+10);setShowStr(true);setStrS(300);setTimeout(()=>setShowStr(false),2500);}
    else{clearInterval(strRef.current);}
    return()=>clearInterval(strRef.current);
  },[strOn,strS]);
  const MEDAL=["🥇","🥈","🥉"];
  const [lName,setLName]=useState(""),[lSub,setLSub]=useState(false),[lBoard,setLBoard]=useState("weekly"),[boards,setBoards]=useState({weekly:[],monthly:[],alltime:[]}),[lLoad,setLLoad]=useState(false);
  const WK=()=>{const n=new Date(),s=new Date(n.getFullYear(),0,1),w=Math.ceil(((n-s)/86400000+s.getDay()+1)/7);return`w_${n.getFullYear()}_${w}`;};
  const MK=()=>{const n=new Date();return`m_${n.getFullYear()}_${String(n.getMonth()+1).padStart(2,"0")}`;};
  const loadB=async()=>{setLLoad(true);const ld=async p=>{try{const r=await window.storage.list(p);const e=await Promise.all(r.keys.map(async k=>{try{const x=await window.storage.get(k,true);return x?JSON.parse(x.value):null;}catch{return null;}}));return e.filter(Boolean).sort((a,b)=>b.points-a.points);}catch{return[];}};const[w,m,a]=await Promise.all([ld(`lw_${WK()}:`),ld(`lm_${MK()}:`),ld("la:")]);setBoards({weekly:w,monthly:m,alltime:a});setLLoad(false);};
  const submitL=async()=>{if(!lName.trim())return;const slug=lName.trim().toLowerCase().replace(/\s+/g,"_"),e={name:lName.trim(),points:pts,drills:doneD.length,rope:ropeDone,journal:journals.length,updated:new Date().toLocaleDateString("en-US",{month:"short",day:"numeric"})};try{await Promise.all([window.storage.set(`lw_${WK()}:${slug}`,JSON.stringify(e),true),window.storage.set(`lm_${MK()}:${slug}`,JSON.stringify(e),true),window.storage.set(`la:${slug}`,JSON.stringify(e),true)]);}catch(x){}setLSub(true);loadB();};
  useEffect(()=>{if(tab==="league")loadB();},[tab]);
  const [journals,setJournals]=useState([]),[jView,setJView]=useState("list"),[jType,setJType]=useState("free"),[eType,setEType]=useState("match"),[mFmt,setMFmt]=useState("singles"),[mood,setMood]=useState(3),[ft,setFt]=useState(""),[ga,setGa]=useState({}),[selJ,setSelJ]=useState(null);
  const eP=()=>({name:"",hand:"",bh:"",styles:[],weapons:[],physical:[],mental:[],notes:""});
  const [oN,setON]=useState(""),[oN2,setON2]=useState(""),[oPt,setOPt]=useState(""),[oR,setOR]=useState(""),[oSc,setOSc]=useState(""),[pt2,setPt2]=useState(eP()),[o1,setO1]=useState(eP()),[o2,setO2]=useState(eP()),[ap,setAp]=useState("o1");
  const up=(s,f,v)=>s(p=>({...p,[f]:v}));
  const tog=(s,f,v)=>s(p=>({...p,[f]:p[f].includes(v)?p[f].filter(x=>x!==v):[...p[f],v]}));
  const saveJ=()=>{
    const entry={id:Date.now(),eType,mood,ft,ga,jType,date:new Date().toLocaleDateString("en-US",{weekday:"short",month:"short",day:"numeric"}),ts:new Date().toISOString(),
      opp:eType==="match"?{mFmt,result:oR,score:oSc,o1:{...o1,name:oN},o2:mFmt==="doubles"?{...o2,name:oN2}:null,partner:mFmt==="doubles"?{...pt2,name:oPt}:null}:null};
    setJournals(p=>[entry,...p]);setJView("list");
    setFt("");setGa({});setMood(3);setEType("match");setJType("free");
    setON("");setON2("");setOPt("");setOR("");setOSc("");
    setPt2(eP());setO1(eP());setO2(eP());setAp("o1");setMFmt("singles");
  };
  const closeDrill=()=>{
    if(activeDrill&&!doneD.includes(activeDrill.id)){setDoneD(d=>[...d,activeDrill.id]);setDHistory(h=>[{drill:activeDrill.title,date:new Date().toLocaleDateString()},...h].slice(0,50));}
    setActiveDrill(null);
  };
  const togCh=(id,p)=>{if(doneCh.includes(id)){setDoneCh(c=>c.filter(x=>x!==id));setPts(x=>x-p);}else{setDoneCh(c=>[...c,id]);setPts(x=>x+p);}};
  const TABS=[{id:"home",icon:"🏠",label:"HOME"},{id:"drills",icon:"⚡",label:"DRILLS"},{id:"challenge",icon:"📅",label:"DAILY"},{id:"prematch",icon:"🎾",label:"MATCH"},{id:"rope",icon:"🪢",label:"ROPE/STR"},{id:"league",icon:"🏅",label:"LEAGUE"},{id:"journal",icon:"📓",label:"JOURNAL"},{id:"profile",icon:"👤",label:"ME"}];
  const L={fontSize:11,fontWeight:700,letterSpacing:2,fontFamily:"'Space Mono',monospace",color:"#4a7a5a"};
  const CARD={background:"#0d1f18",borderRadius:16,padding:18,marginBottom:12,border:"1px solid #1a2820"};
  const ch=(a,c="#00FF87")=>({padding:"5px 10px",borderRadius:20,border:"none",fontSize:11,fontWeight:700,cursor:"pointer",marginBottom:5,marginRight:5,background:a?c+"22":"#0d1f18",color:a?c:"#4a7a5a",outline:a?`1px solid ${c}55`:"1px solid #1a2820"});
  const PForm=({ps,s,nv,sn,color})=>(<>
    <input value={nv} onChange={e=>sn(e.target.value)} placeholder="Player name" style={{width:"100%",padding:"9px 12px",borderRadius:10,fontSize:13,marginBottom:12,background:"#0a1410",border:`1px solid ${color}33`,color:"#fff",outline:"none",display:"block"}}/>
    <div style={{...L,color:"#FF6B35",marginBottom:6}}>HAND</div>
    <div style={{display:"flex",gap:8,marginBottom:12}}>{HANDS.map(h=><button key={h} onClick={()=>up(s,"hand",ps.hand===h?"":h)} style={{flex:1,padding:"8px",borderRadius:10,border:"none",fontSize:12,fontWeight:700,cursor:"pointer",background:ps.hand===h?"#FF6B3522":"#0d1f18",color:ps.hand===h?"#FF6B35":"#4a7a5a",outline:ps.hand===h?"1px solid #FF6B3555":"1px solid #1a2820"}}>{h==="Right-Handed"?"✋ R":"🤚 L"}</button>)}</div>
    <div style={{...L,color:"#FF6B35",marginBottom:6}}>BACKHAND</div>
    <div style={{display:"flex",flexWrap:"wrap",marginBottom:12}}>{BH.map(b=><button key={b} onClick={()=>up(s,"bh",ps.bh===b?"":b)} style={ch(ps.bh===b,"#FF6B35")}>{b}</button>)}</div>
    <div style={{...L,color:"#60A5FA",marginBottom:6}}>PLAYING STYLE</div>
    <div style={{display:"flex",flexWrap:"wrap",marginBottom:12}}>{STYLES.map(x=><button key={x} onClick={()=>tog(s,"styles",x)} style={ch(ps.styles.includes(x),"#60A5FA")}>{x}</button>)}</div>
    <div style={{...L,color:"#FBBF24",marginBottom:6}}>KEY WEAPONS</div>
    <div style={{display:"flex",flexWrap:"wrap",marginBottom:12}}>{WEAPONS.map(x=><button key={x} onClick={()=>tog(s,"weapons",x)} style={ch(ps.weapons.includes(x),"#FBBF24")}>{x}</button>)}</div>
    <div style={{...L,color:"#34D399",marginBottom:6}}>PHYSICAL</div>
    <div style={{display:"flex",flexWrap:"wrap",marginBottom:12}}>{PHYSICAL.map(x=><button key={x} onClick={()=>tog(s,"physical",x)} style={ch(ps.physical.includes(x),"#34D399")}>{x}</button>)}</div>
    <div style={{...L,color:"#C084FC",marginBottom:6}}>MENTAL TRAITS</div>
    <div style={{display:"flex",flexWrap:"wrap",marginBottom:12}}>{MENTAL_T.map(x=><button key={x} onClick={()=>tog(s,"mental",x)} style={ch(ps.mental.includes(x),"#C084FC")}>{x}</button>)}</div>
    <div style={{...L,marginBottom:6}}>NOTES</div>
    <textarea value={ps.notes} onChange={e=>up(s,"notes",e.target.value)} placeholder="Anything else..." rows={2} style={{width:"100%",padding:"9px 12px",borderRadius:10,fontSize:13,background:"#0d1f18",border:"1px solid #1a3028",color:"#fff",outline:"none",resize:"none",lineHeight:1.5,display:"block"}}/>
  </>);
  const PView=({p,label,color,last})=>{
    if(!p?.name)return null;
    return <div style={{marginBottom:14,paddingBottom:14,borderBottom:last?"none":"1px solid #1a2820"}}>
      <div style={{...L,color,marginBottom:6}}>{label.toUpperCase()}</div>
      <div style={{fontSize:14,fontWeight:700,color:"#fff",marginBottom:8}}>{p.name}</div>
      {(p.hand||p.bh)&&<div style={{display:"flex",flexWrap:"wrap",gap:5,marginBottom:8}}>{p.hand&&<span style={{fontSize:11,padding:"2px 9px",borderRadius:20,background:"#FF6B3518",color:"#FF6B35"}}>{p.hand==="Right-Handed"?"✋ Right":"🤚 Left"}</span>}{p.bh&&<span style={{fontSize:11,padding:"2px 9px",borderRadius:20,background:"#FF6B3518",color:"#FF6B35"}}>{p.bh}</span>}</div>}
      {[{l:"Style",d:p.styles,c:"#60A5FA"},{l:"Weapons",d:p.weapons,c:"#FBBF24"},{l:"Physical",d:p.physical,c:"#34D399"},{l:"Mental",d:p.mental,c:"#C084FC"}].map((cat,i)=>cat.d?.length>0&&<div key={i} style={{marginBottom:7}}><div style={{fontSize:9,fontWeight:700,color:cat.c,letterSpacing:1,marginBottom:4}}>{cat.l.toUpperCase()}</div><div style={{display:"flex",flexWrap:"wrap",gap:4}}>{cat.d.map(t=><span key={t} style={{fontSize:11,padding:"2px 7px",borderRadius:20,background:cat.c+"18",color:cat.c}}>{t}</span>)}</div></div>)}
      {p.notes&&<div style={{fontSize:12,color:"#7a9a8a",marginTop:5,lineHeight:1.5}}>{p.notes}</div>}
    </div>;
  };
  return (
    <div style={{minHeight:"100vh",background:"#070f0b",color:"#fff",fontFamily:"'DM Sans',sans-serif",maxWidth:430,margin:"0 auto",paddingBottom:90}}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;700;900&family=Space+Mono:wght@700&display=swap');*{box-sizing:border-box;margin:0;padding:0;}::-webkit-scrollbar{display:none;}textarea,input{font-family:'DM Sans',sans-serif;}`}</style>
      <div style={{padding:"16px 20px 0",background:"linear-gradient(180deg,#0a1a13 0%,transparent 100%)",position:"sticky",top:0,zIndex:10,backdropFilter:"blur(20px)"}}>
        <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",paddingBottom:12}}>
          <div><div style={{...L,color:"#00FF87"}}>MENTAL TENNIS</div><div style={{fontSize:20,fontWeight:900,color:"#fff",lineHeight:1.1}}>Mind Training</div></div>
          <div style={{textAlign:"right"}}><div style={L}>POINTS</div><div style={{fontSize:22,fontWeight:900,color:"#00FF87",fontFamily:"monospace"}}>{pts}</div></div>
        </div>
      </div>
      <div style={{padding:"0 20px"}}>
        {tab==="home"&&<div style={{paddingTop:14}}>
          <div style={{background:"linear-gradient(135deg,#0d2018,#0a1a13)",border:"1px solid #00FF8733",borderRadius:18,padding:18,marginBottom:14}}>
            <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:8}}><span>💡</span><span style={{...L,color:"#00FF87"}}>COACH TIP · TODAY</span></div>
            <div style={{fontSize:14,color:"#c8e8d8",lineHeight:1.6,fontWeight:600}}>{TIPS[tip]}</div>
            <button onClick={()=>setTip(t=>(t+1)%TIPS.length)} style={{marginTop:8,fontSize:11,color:"#4a7a5a",background:"transparent",border:"none",cursor:"pointer",padding:0}}>Next tip →</button>
          </div>
          <div style={{...CARD,display:"flex",alignItems:"center",gap:14}}><Ring value={doneD.length} max={DRILLS.length} color="#00FF87" size={66}/><div><div style={{fontSize:20,fontWeight:900,color:"#fff"}}>{doneD.length}/{DRILLS.length}</div><div style={{fontSize:12,color:"#7a9a8a"}}>Drills Completed</div><div style={{fontSize:11,color:"#4a7a5a",marginTop:2}}>Keep it up! 💪</div></div></div>
          <div style={{marginBottom:14}}><div style={{...L,marginBottom:10}}>QUICK START</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>{DRILLS.slice(0,4).map(d=><div key={d.id} onClick={()=>setActiveDrill(d)} style={{background:"#0d1f18",borderRadius:14,padding:14,cursor:"pointer",border:doneD.includes(d.id)?`1px solid ${d.color}55`:"1px solid #1a2820",position:"relative"}}>{doneD.includes(d.id)&&<div style={{position:"absolute",top:8,right:8,fontSize:11}}>✅</div>}<div style={{fontSize:20,marginBottom:6}}>{d.emoji}</div><div style={{fontSize:12,fontWeight:700,color:"#fff"}}>{d.title}</div><div style={{fontSize:10,color:d.color,marginTop:2}}>{d.tag}</div></div>)}</div></div>
          <div style={{background:"linear-gradient(135deg,#1a0a2a,#0a1020)",borderRadius:14,padding:18,border:"1px solid #C084FC33"}}><div style={{...L,color:"#C084FC",marginBottom:8}}>TENNIS WISDOM</div><div style={{fontSize:13,color:"#e0d0f8",lineHeight:1.7,fontStyle:"italic"}}>"In tennis, you don't lose your energy — you lose your focus on the next point."</div><div style={{fontSize:11,color:"#7a5a9a",marginTop:6}}>— Core principle of sport psychology</div></div>
        </div>}
        {tab==="drills"&&<div style={{paddingTop:14}}><div style={{...L,marginBottom:12}}>ALL DRILLS · {DRILLS.length}</div>{DRILLS.map(d=><div key={d.id} onClick={()=>setActiveDrill(d)} style={{background:"#0d1f18",border:`1px solid ${d.color}${doneD.includes(d.id)?"55":"18"}`,borderRadius:14,padding:18,marginBottom:10,cursor:"pointer",position:"relative",overflow:"hidden"}}><div style={{position:"absolute",top:0,right:0,width:70,height:70,background:`radial-gradient(circle at top right,${d.color}12,transparent)`}}/>{doneD.includes(d.id)&&<div style={{position:"absolute",top:12,right:12,fontSize:11,color:"#00FF87",fontWeight:700,fontFamily:"monospace"}}>✓ DONE</div>}<div style={{fontSize:28,marginBottom:7}}>{d.emoji}</div><div style={{fontSize:13,fontWeight:700,color:"#fff",marginBottom:5,fontFamily:"'Space Mono',monospace"}}>{d.title}</div><span style={{fontSize:9,fontWeight:700,letterSpacing:2,color:d.color,background:d.color+"18",padding:"2px 8px",borderRadius:20,display:"inline-block",marginBottom:7}}>{d.tag}</span><div style={{fontSize:12,color:"#7a9a8a",lineHeight:1.5}}>{d.desc}</div><div style={{marginTop:10,display:"flex",alignItems:"center",gap:5}}><div style={{width:16,height:2,background:d.color,borderRadius:2}}/><span style={{fontSize:10,color:d.color,fontWeight:700}}>START · 3 MIN</span></div></div>)}</div>}
        {tab==="challenge"&&<div style={{paddingTop:14}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}><div style={L}>TODAY'S CHALLENGES</div><div style={{fontSize:12,color:"#FBBF24"}}>{pts} pts</div></div>{CHALLENGES.map(c=>{const done=doneCh.includes(c.id);return(<div key={c.id} onClick={()=>togCh(c.id,c.points)} style={{background:done?"#0d2018":"#0d1f18",border:done?"1px solid #00FF8744":"1px solid #1a2820",borderRadius:14,padding:14,marginBottom:8,cursor:"pointer",display:"flex",alignItems:"flex-start",gap:12}}><div style={{width:22,height:22,borderRadius:7,flexShrink:0,marginTop:1,background:done?"#00FF87":"transparent",border:done?"none":"2px solid #2a4a3a",display:"flex",alignItems:"center",justifyContent:"center",color:"#001a0a",fontWeight:900,fontSize:13}}>{done?"✓":""}</div><div style={{flex:1}}><div style={{fontSize:13,color:done?"#7a9a8a":"#c8e8d8",lineHeight:1.5,textDecoration:done?"line-through":"none"}}>{c.text}</div><div style={{fontSize:11,color:"#FBBF24",marginTop:4,fontFamily:"monospace"}}>+{c.points} pts</div></div></div>);})} <div style={{...CARD,textAlign:"center",marginTop:6}}><div style={{fontSize:28,marginBottom:6}}>🏅</div><div style={{fontSize:14,fontWeight:700,color:"#fff",marginBottom:4}}>{CHALLENGES.reduce((a,c)=>a+c.points,0)} pts available today</div><div style={{fontSize:12,color:"#7a9a8a"}}>Tap each challenge when complete</div></div></div>}
        {tab==="prematch"&&<div style={{paddingTop:14}}><div style={{...L,marginBottom:4}}>PRE-MATCH TOOLKIT</div><div style={{fontSize:12,color:"#4a6a5a",marginBottom:14}}>Mental prep 10 minutes before you play</div><MatchTimer/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginTop:14}}>{TOOLS.map((t,i)=><div key={i} onClick={()=>setPmStep(pmStep===i?null:i)} style={{background:"#0d1f18",borderRadius:14,padding:14,cursor:"pointer",border:pmStep===i?"1px solid #FF6B3555":"1px solid #1a2820"}}><div style={{fontSize:24,marginBottom:7}}>{t.icon}</div><div style={{fontSize:13,fontWeight:700,color:"#fff",marginBottom:3}}>{t.label}</div><div style={{fontSize:11,color:"#4a7a5a",lineHeight:1.4}}>{t.desc}</div></div>)}</div>{pmStep!==null&&<div style={{marginTop:12,background:"#0d1a14",border:"1px solid #FF6B3533",borderRadius:14,padding:18}}><div style={{fontSize:14,fontWeight:800,color:"#FF6B35",marginBottom:8}}>{TOOLS[pmStep].icon} {TOOLS[pmStep].label}</div><div style={{fontSize:13,color:"#a8c8b8",lineHeight:1.7}}>{TOOLS[pmStep].detail}</div></div>}</div>}
        {tab==="rope"&&<div style={{paddingTop:14}}>
          {showRope&&<div style={{position:"fixed",inset:0,background:"#000b",zIndex:200,display:"flex",alignItems:"center",justifyContent:"center",flexDirection:"column"}}><div style={{fontSize:64,marginBottom:8}}>🎉</div><div style={{fontSize:24,fontWeight:900,color:"#00FF87",marginBottom:4}}>800 Done!</div><div style={{fontSize:14,color:"#c8e8d8"}}>+{RP} points!</div></div>}
          <div style={{...L,marginBottom:14}}>OFF-COURT · ROPE / STRETCH</div>
          <div style={{background:"linear-gradient(135deg,#0d2018,#0a1a13)",border:"1px solid #34D39933",borderRadius:20,padding:24,marginBottom:12,textAlign:"center"}}><div style={{position:"relative",display:"inline-block",marginBottom:12}}><Ring value={ropeTotal%RG} max={RG} color="#34D399" size={130}/><div style={{position:"absolute",inset:0,display:"flex",alignItems:"center",justifyContent:"center",flexDirection:"column"}}><div style={{fontSize:28,fontWeight:900,color:"#fff",fontFamily:"monospace",lineHeight:1}}>{ropeTotal%RG}</div><div style={{fontSize:11,color:"#4a7a5a",marginTop:2}}>/ {RG}</div></div></div><div style={{fontSize:12,color:"#7a9a8a",marginBottom:4}}>jumps in current round</div><div style={{fontSize:11,color:"#34D399",fontFamily:"monospace",fontWeight:700}}>{ropeDone} × 800 completed · {ropeDone*RP} pts</div></div>
          <div style={{...CARD,display:"flex",gap:10,alignItems:"center"}}><input type="number" value={ropeIn} onChange={e=>setRopeIn(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addRope()} placeholder="How many jumps?" style={{flex:1,padding:"12px 14px",borderRadius:12,fontSize:15,fontWeight:700,background:"#0a1410",border:"1px solid #1a3028",color:"#fff",outline:"none"}}/><button onClick={addRope} style={{padding:"12px 18px",borderRadius:12,border:"none",background:"#34D399",color:"#001a0a",fontSize:14,fontWeight:900,cursor:"pointer",whiteSpace:"nowrap"}}>+ ADD</button></div>
          <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:8,marginBottom:12}}>{[{l:"Total Jumps",v:ropeTotal.toLocaleString(),c:"#34D399"},{l:"Rounds of 800",v:ropeDone,c:"#00FF87"},{l:"Pts Earned",v:ropeDone*RP,c:"#FBBF24"}].map((s,i)=><div key={i} style={{background:"#0d1f18",borderRadius:12,padding:12,textAlign:"center",border:"1px solid #1a2820"}}><div style={{fontSize:17,fontWeight:900,color:s.c,fontFamily:"monospace"}}>{s.v}</div><div style={{fontSize:10,color:"#4a7a5a",marginTop:2,lineHeight:1.3}}>{s.l}</div></div>)}</div>
          {ropeSess.length>0&&<div style={CARD}><div style={{...L,marginBottom:10}}>SESSION LOG</div>{ropeSess.map((s,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"8px 0",borderBottom:i<ropeSess.length-1?"1px solid #1a2820":"none"}}><div style={{display:"flex",alignItems:"center",gap:8}}><span>🪢</span><span style={{fontSize:13,fontWeight:700,color:"#00FF87",fontFamily:"monospace"}}>+{s.n}</span><span style={{fontSize:12,color:"#7a9a8a"}}>jumps</span></div><span style={{fontSize:11,color:"#4a7a5a"}}>{s.date} {s.time}</span></div>)}</div>}
          <div style={{borderTop:"1px solid #1a2820",paddingTop:18,marginTop:4}}>
            <div style={{...L,color:"#C084FC",marginBottom:3}}>STRETCH CHECK-IN</div>
            <div style={{fontSize:12,color:"#4a6a5a",marginBottom:12}}>5-minute timer · +10 pts per stretch</div>
            {showStr&&<div style={{background:"#1a0a2a",border:"1px solid #C084FC55",borderRadius:14,padding:"12px 18px",marginBottom:12,textAlign:"center"}}><span style={{fontSize:20}}>🧘</span><span style={{fontSize:14,fontWeight:700,color:"#C084FC",marginLeft:8}}>Stretch complete! +10 pts</span></div>}
            <div style={{background:"linear-gradient(135deg,#120a1a,#0a0d1a)",border:"1px solid #C084FC33",borderRadius:18,padding:20,marginBottom:12,textAlign:"center"}}><div style={{position:"relative",display:"inline-block",marginBottom:12}}><Ring value={300-strS} max={300} color="#C084FC" size={110}/><div style={{position:"absolute",inset:0,display:"flex",alignItems:"center",justifyContent:"center",flexDirection:"column"}}><span style={{fontSize:22,fontWeight:900,color:"#fff",fontFamily:"monospace"}}>{String(Math.floor(strS/60)).padStart(2,"0")}:{String(strS%60).padStart(2,"0")}</span><span style={{fontSize:10,color:"#6a4a8a",marginTop:2}}>5:00 goal</span></div></div><div style={{fontSize:12,color:"#7a9a8a",marginBottom:14}}>{strOn?"Stretching... hold it! 🧘":"Start your 5-minute stretch"}</div><div style={{display:"flex",gap:8,justifyContent:"center"}}><button onClick={()=>{setStrS(300);setStrOn(false);}} style={{padding:"8px 14px",borderRadius:10,border:"1px solid #2a1a3a",background:"transparent",color:"#6a4a8a",fontSize:12,cursor:"pointer"}}>Reset</button><button onClick={()=>setStrOn(x=>!x)} style={{padding:"8px 24px",borderRadius:10,border:"none",background:strOn?"#2a1a3a":"#C084FC",color:strOn?"#6a4a8a":"#1a0a2a",fontSize:12,fontWeight:700,cursor:"pointer"}}>{strOn?"Pause":"Start"}</button></div></div>
            <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:12}}><div style={{...CARD,textAlign:"center",marginBottom:0}}><div style={{fontSize:26,fontWeight:900,color:"#C084FC",fontFamily:"monospace"}}>{strCnt}</div><div style={{fontSize:11,color:"#4a7a5a",marginTop:2}}>Stretches Done</div></div><div style={{...CARD,textAlign:"center",marginBottom:0}}><div style={{fontSize:26,fontWeight:900,color:"#FBBF24",fontFamily:"monospace"}}>{strCnt*10}</div><div style={{fontSize:11,color:"#4a7a5a",marginTop:2}}>Pts from Stretching</div></div></div>
            {strLog.length>0&&<div style={CARD}><div style={{...L,marginBottom:10}}>STRETCH LOG</div>{strLog.slice(0,6).map((s,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"7px 0",borderBottom:i<Math.min(strLog.length,6)-1?"1px solid #1a2820":"none"}}><div style={{display:"flex",alignItems:"center",gap:7}}><span>🧘</span><span style={{fontSize:13,color:"#c8e8d8"}}>5 min stretch</span></div><span style={{fontSize:11,color:"#4a7a5a"}}>{s.date} {s.time}</span></div>)}</div>}
          </div>
        </div>}
        {tab==="league"&&<div style={{paddingTop:14}}>
          <div style={{...L,marginBottom:4}}>LEAGUE LEADERBOARD</div>
          <div style={{fontSize:12,color:"#4a6a5a",marginBottom:12}}>Compete with players worldwide</div>
          <div style={{background:"linear-gradient(135deg,#1a0f2a,#0a1020)",border:"1px solid #C084FC33",borderRadius:18,padding:16,marginBottom:12}}><div style={{...L,color:"#C084FC",marginBottom:8}}>YOUR ENTRY</div>{!lSub?<><div style={{fontSize:12,color:"#7a9a8a",marginBottom:8,lineHeight:1.5}}>Join all 3 boards with your score ({pts} pts).</div><div style={{display:"flex",gap:8}}><input value={lName} onChange={e=>setLName(e.target.value)} onKeyDown={e=>e.key==="Enter"&&submitL()} placeholder="Your player name" style={{flex:1,padding:"11px 12px",borderRadius:10,fontSize:13,background:"#0d1020",border:"1px solid #2a1a3a",color:"#fff",outline:"none"}}/><button onClick={submitL} disabled={!lName.trim()} style={{padding:"11px 14px",borderRadius:10,border:"none",background:"#C084FC",color:"#1a0a2a",fontSize:13,fontWeight:900,cursor:"pointer",opacity:!lName.trim()?0.4:1}}>JOIN</button></div></>:<div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8}}><div><div style={{fontSize:14,fontWeight:700,color:"#fff"}}>{lName}</div><div style={{fontSize:12,color:"#C084FC",marginTop:2}}>{pts} pts on all boards</div></div><span style={{fontSize:26}}>🎾</span></div><button onClick={submitL} style={{width:"100%",padding:"9px",borderRadius:10,border:"1px solid #C084FC44",background:"transparent",color:"#C084FC",fontSize:12,fontWeight:700,cursor:"pointer"}}>Update My Score →</button></div>}</div>
          <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:6,marginBottom:12}}>{[{id:"weekly",label:"Weekly",icon:"📅",sub:"Resets Mon",color:"#60A5FA"},{id:"monthly",label:"Monthly",icon:"🗓️",sub:"Resets 1st",color:"#FBBF24"},{id:"alltime",label:"All Time",icon:"🏆",sub:"Never resets",color:"#00FF87"}].map(b=><div key={b.id} onClick={()=>setLBoard(b.id)} style={{background:lBoard===b.id?b.color+"22":"#0d1f18",border:lBoard===b.id?`1px solid ${b.color}66`:"1px solid #1a2820",borderRadius:12,padding:"11px 6px",cursor:"pointer",textAlign:"center"}}><div style={{fontSize:18,marginBottom:3}}>{b.icon}</div><div style={{fontSize:10,fontWeight:700,color:lBoard===b.id?b.color:"#7a9a8a",fontFamily:"'Space Mono',monospace"}}>{b.label}</div><div style={{fontSize:9,color:"#3a5a4a",marginTop:1}}>{b.sub}</div></div>)}</div>
          <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8}}><div style={{...L,color:lBoard==="weekly"?"#60A5FA":lBoard==="monthly"?"#FBBF24":"#00FF87"}}>{lBoard==="weekly"?"THIS WEEK":lBoard==="monthly"?"THIS MONTH":"ALL TIME"}</div><button onClick={loadB} style={{fontSize:11,color:"#4a7a5a",background:"transparent",border:"none",cursor:"pointer"}}>{lLoad?"Loading...":"↻ Refresh"}</button></div>
          {lLoad&&<div style={{textAlign:"center",padding:"24px",color:"#4a7a5a",fontSize:13}}>Loading...</div>}
          {!lLoad&&boards[lBoard].length===0&&<div style={{textAlign:"center",padding:"32px 20px"}}><div style={{fontSize:36,marginBottom:8}}>🏅</div><div style={{fontSize:14,fontWeight:700,color:"#fff",marginBottom:5}}>No players yet</div><div style={{fontSize:12,color:"#4a7a5a"}}>Be the first!</div></div>}
          {!lLoad&&boards[lBoard].map((p,i)=>{const bc=lBoard==="weekly"?"#60A5FA":lBoard==="monthly"?"#FBBF24":"#00FF87";const isMe=lName&&p.name.toLowerCase()===lName.trim().toLowerCase();return(<div key={i} style={{background:isMe?"#0d2018":"#0d1f18",border:isMe?`1px solid ${bc}55`:"1px solid #1a2820",borderRadius:14,padding:12,marginBottom:8,display:"flex",alignItems:"center",gap:10}}><div style={{fontSize:i<3?22:12,fontWeight:900,color:"#FBBF24",fontFamily:"monospace",minWidth:24,textAlign:"center"}}>{i<3?MEDAL[i]:`#${i+1}`}</div><div style={{flex:1}}><div style={{display:"flex",alignItems:"center",gap:6}}><span style={{fontSize:13,fontWeight:700,color:"#fff"}}>{p.name}</span>{isMe&&<span style={{fontSize:9,color:"#00FF87",fontWeight:700,background:"#00FF8720",padding:"1px 6px",borderRadius:10}}>YOU</span>}</div><div style={{display:"flex",gap:8,marginTop:3}}><span style={{fontSize:10,color:"#4a7a5a"}}>⚡{p.drills}</span><span style={{fontSize:10,color:"#4a7a5a"}}>🪢{p.rope}</span><span style={{fontSize:10,color:"#4a7a5a"}}>📓{p.journal}</span><span style={{fontSize:10,color:"#3a5a4a"}}>· {p.updated}</span></div></div><div style={{textAlign:"right"}}><div style={{fontSize:17,fontWeight:900,color:bc,fontFamily:"monospace"}}>{p.points}</div><div style={{fontSize:9,color:"#4a7a5a"}}>pts</div></div></div>);})}
          <div style={{textAlign:"center",marginTop:4,fontSize:10,color:"#2a4a3a",paddingBottom:6}}>Weekly resets Monday · Monthly resets 1st · All Time never resets</div>
        </div>}
        {tab==="journal"&&<div style={{paddingTop:14}}>
          {jView==="list"&&<><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:14}}><div style={L}>MY JOURNAL</div><button onClick={()=>setJView("new")} style={{padding:"7px 14px",borderRadius:10,border:"none",background:"#00FF87",color:"#001a0a",fontSize:12,fontWeight:700,cursor:"pointer",fontFamily:"'Space Mono',monospace"}}>+ NEW</button></div>{journals.length===0?<div style={{textAlign:"center",padding:"44px 20px"}}><div style={{fontSize:44,marginBottom:12}}>📓</div><div style={{fontSize:16,fontWeight:700,color:"#fff",marginBottom:7}}>Start your journal</div><div style={{fontSize:13,color:"#4a7a5a",marginBottom:20,lineHeight:1.6}}>Track your mental game after every match and practice</div><button onClick={()=>setJView("new")} style={{padding:"11px 24px",borderRadius:12,border:"none",background:"#00FF87",color:"#001a0a",fontSize:14,fontWeight:700,cursor:"pointer"}}>Write First Entry</button></div>:journals.map((j,i)=>{const me=["😤","😟","😐","🙂","🤩"][j.mood-1];const tc={match:"#00FF87",practice:"#60A5FA",mental:"#C084FC"}[j.eType]||"#4a7a5a";const prev=j.jType==="free"?j.ft:Object.values(j.ga).filter(Boolean).join(" · ");const op=j.opp;return <div key={j.id} onClick={()=>{setSelJ(j);setJView("detail");}} style={{background:"#0d1f18",borderRadius:14,padding:16,marginBottom:8,cursor:"pointer",border:`1px solid ${tc}22`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:7}}><span style={{fontSize:9,fontWeight:700,letterSpacing:2,color:tc,background:tc+"18",padding:"2px 8px",borderRadius:20}}>{j.eType?.toUpperCase()}{op?.mFmt?` · ${op.mFmt.toUpperCase()}`:""}</span><div style={{display:"flex",alignItems:"center",gap:7}}><span style={{fontSize:15}}>{me}</span><span style={{fontSize:11,color:"#4a7a5a"}}>{j.date}</span></div></div><div style={{fontSize:13,color:"#c8e8d8",lineHeight:1.5,overflow:"hidden",display:"-webkit-box",WebkitLineClamp:2,WebkitBoxOrient:"vertical"}}>{prev||"—"}</div>{op?.o1?.name&&<div style={{display:"flex",alignItems:"center",gap:5,marginTop:5,flexWrap:"wrap"}}>{op.partner?.name&&<span style={{fontSize:10,color:"#00FF87"}}>🤝 {op.partner.name} ·</span>}<span style={{fontSize:11,color:"#7a9a8a"}}>vs {op.o1.name}{op.o2?.name?` & ${op.o2.name}`:""}</span>{op.result&&<span style={{fontSize:10,fontWeight:900,padding:"1px 7px",borderRadius:20,background:op.result==="W"?"#00FF8722":"#FF6B3522",color:op.result==="W"?"#00FF87":"#FF6B35"}}>{op.result}</span>}{op.score&&<span style={{fontSize:10,color:"#4a7a5a"}}>{op.score}</span>}</div>}</div>;})}</>}
          {jView==="detail"&&selJ&&<div><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:16}}><button onClick={()=>setJView("list")} style={{background:"#0d1f18",border:"1px solid #1a3028",borderRadius:10,padding:"7px 12px",color:"#7a9a8a",fontSize:13,cursor:"pointer"}}>← Back</button><div style={{fontSize:12,color:"#4a7a5a"}}>{selJ.date}</div></div><div style={{background:"#0d1f18",borderRadius:18,padding:22}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}><span style={{fontSize:10,fontWeight:700,letterSpacing:2,color:{match:"#00FF87",practice:"#60A5FA",mental:"#C084FC"}[selJ.eType]||"#4a7a5a"}}>{selJ.eType?.toUpperCase()}{selJ.opp?.mFmt?` · ${selJ.opp.mFmt.toUpperCase()}`:""} · {selJ.jType?.toUpperCase()}</span><span style={{fontSize:24}}>{["😤","😟","😐","🙂","🤩"][selJ.mood-1]}</span></div>{selJ.jType==="free"?<div style={{fontSize:14,color:"#c8e8d8",lineHeight:1.8,whiteSpace:"pre-wrap"}}>{selJ.ft}</div>:<div style={{display:"flex",flexDirection:"column",gap:14}}>{GUIDED[selJ.eType]?.map((q,i)=>selJ.ga[q]&&<div key={i}><div style={{fontSize:11,color:"#4a7a5a",marginBottom:5,fontWeight:700}}>{q}</div><div style={{fontSize:14,color:"#c8e8d8",lineHeight:1.6}}>{selJ.ga[q]}</div></div>)}</div>}{selJ.opp&&<div style={{marginTop:18,background:"#0a1410",border:"1px solid #1a3028",borderRadius:12,padding:14}}><div style={{...L,color:"#FF6B35",marginBottom:4}}>🎾 PLAYER PROFILES</div><div style={{display:"flex",alignItems:"center",gap:7,marginBottom:12}}>{selJ.opp.result&&<span style={{fontSize:12,fontWeight:900,padding:"2px 10px",borderRadius:20,background:selJ.opp.result==="W"?"#00FF8722":"#FF6B3522",color:selJ.opp.result==="W"?"#00FF87":"#FF6B35"}}>{selJ.opp.result}</span>}{selJ.opp.score&&<span style={{fontSize:12,color:"#7a9a8a"}}>{selJ.opp.score}</span>}</div>{selJ.opp.mFmt==="doubles"&&<PView p={selJ.opp.partner} label="My Partner" color="#00FF87"/>}<PView p={selJ.opp.o1} label={selJ.opp.mFmt==="doubles"?"Opponent 1":"Opponent"} color="#FF6B35"/>{selJ.opp.mFmt==="doubles"&&<PView p={selJ.opp.o2} label="Opponent 2" color="#FF6B35" last/>}</div>}</div></div>}
          {jView==="new"&&<div><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:16}}><button onClick={()=>setJView("list")} style={{background:"#0d1f18",border:"1px solid #1a3028",borderRadius:10,padding:"7px 12px",color:"#7a9a8a",fontSize:13,cursor:"pointer"}}>← Back</button><div style={{fontSize:14,fontWeight:700,color:"#fff"}}>New Entry</div></div>
          <div style={{marginBottom:14}}><div style={{...L,marginBottom:7}}>TYPE</div><div style={{display:"flex",gap:8}}>{[{id:"match",label:"🏆 Match"},{id:"practice",label:"⚡ Practice"},{id:"mental",label:"🧠 Mental"}].map(t=><button key={t.id} onClick={()=>setEType(t.id)} style={{flex:1,padding:"9px 5px",borderRadius:10,border:"none",fontSize:12,fontWeight:700,cursor:"pointer",background:eType===t.id?"#00FF87":"#0d1f18",color:eType===t.id?"#001a0a":"#7a9a8a"}}>{t.label}</button>)}</div></div>
          {eType==="match"&&<div style={{marginBottom:14}}><div style={{...L,marginBottom:7}}>FORMAT</div><div style={{display:"flex",gap:8}}>{[{id:"singles",label:"👤 Singles"},{id:"doubles",label:"👥 Doubles"}].map(f=><button key={f.id} onClick={()=>setMFmt(f.id)} style={{flex:1,padding:"9px",borderRadius:10,border:"none",fontSize:13,fontWeight:700,cursor:"pointer",background:mFmt===f.id?"#FF6B3522":"#0d1f18",color:mFmt===f.id?"#FF6B35":"#4a7a5a",outline:mFmt===f.id?"1px solid #FF6B3555":"1px solid #1a2820"}}>{f.label}</button>)}</div></div>}
          <div style={{marginBottom:14}}><div style={{...L,marginBottom:7}}>HOW DID YOU FEEL?</div><div style={{display:"flex",gap:6}}>{[{v:1,e:"😤"},{v:2,e:"😟"},{v:3,e:"😐"},{v:4,e:"🙂"},{v:5,e:"🤩"}].map(m=><button key={m.v} onClick={()=>setMood(m.v)} style={{flex:1,padding:"11px 3px",borderRadius:12,border:"none",fontSize:20,cursor:"pointer",background:mood===m.v?"#0d2818":"#0d1f18",outline:mood===m.v?"2px solid #00FF87":"2px solid transparent"}}>{m.e}</button>)}</div></div>
          {eType==="match"&&(()=>{const pm={o1:{state:o1,setter:setO1,name:oN,setName:setON,label:mFmt==="singles"?"Opponent":"Opponent 1",color:"#FF6B35"},o2:{state:o2,setter:setO2,name:oN2,setName:setON2,label:"Opponent 2",color:"#FF6B35"},partner:{state:pt2,setter:setPt2,name:oPt,setName:setOPt,label:"My Partner",color:"#00FF87"}};const pks=mFmt==="singles"?["o1"]:["partner","o1","o2"];const cur=pm[ap];return <div style={{background:"#0a1410",border:"1px solid #1a3028",borderRadius:14,padding:16,marginBottom:14}}><div style={{...L,color:"#FF6B35",marginBottom:12}}>🎾 PLAYER PROFILES</div><div style={{display:"flex",gap:7,marginBottom:10}}><input value={oSc} onChange={e=>setOSc(e.target.value)} placeholder="Score (e.g. 6-4, 3-6, 6-3)" style={{flex:1,padding:"9px 12px",borderRadius:10,fontSize:13,background:"#0d1f18",border:"1px solid #1a3028",color:"#fff",outline:"none"}}/><div style={{display:"flex",gap:5}}>{["W","L"].map(r=><button key={r} onClick={()=>setOR(oR===r?"":r)} style={{width:38,height:38,borderRadius:10,border:"none",fontWeight:900,fontSize:13,cursor:"pointer",background:oR===r?(r==="W"?"#00FF87":"#FF6B35"):"#0d1f18",color:oR===r?"#001a0a":(r==="W"?"#00FF87":"#FF6B35"),outline:oR===r?"none":`1px solid ${r==="W"?"#00FF8744":"#FF6B3544"}`}}>{r}</button>)}</div></div><div style={{display:"flex",gap:5,marginBottom:14}}>{pks.map(k=>{const p=pm[k];const isA=ap===k;return <button key={k} onClick={()=>setAp(k)} style={{flex:1,padding:"8px 5px",borderRadius:10,border:"none",fontSize:11,fontWeight:700,cursor:"pointer",background:isA?p.color+"22":"#0d1f18",color:isA?p.color:"#4a7a5a",outline:isA?`1px solid ${p.color}55`:"1px solid #1a2820"}}>{p.label}{(p.name||p.state.styles.length>0)&&<span style={{display:"block",fontSize:9,marginTop:1,opacity:0.7}}>{p.name||"✓"}</span>}</button>;})}</div><PForm ps={cur.state} s={cur.setter} nv={cur.name} sn={cur.setName} color={cur.color}/></div>;})()} 
          <div style={{display:"flex",background:"#0d1f18",borderRadius:12,padding:4,marginBottom:14}}>{[{id:"free",label:"Free Write"},{id:"guided",label:"Guided Questions"}].map(f=><button key={f.id} onClick={()=>setJType(f.id)} style={{flex:1,padding:"8px",borderRadius:9,border:"none",fontSize:12,fontWeight:700,cursor:"pointer",fontFamily:"'Space Mono',monospace",background:jType===f.id?"#00FF87":"transparent",color:jType===f.id?"#001a0a":"#4a7a5a"}}>{f.label}</button>)}</div>
          {jType==="free"&&<textarea value={ft} onChange={e=>setFt(e.target.value)} placeholder="Write freely about your match, practice, or mental state..." rows={7} style={{width:"100%",padding:"13px 14px",borderRadius:12,fontSize:14,background:"#0d1f18",border:"1px solid #1a3028",color:"#fff",outline:"none",resize:"vertical",lineHeight:1.6,marginBottom:14,display:"block"}}/>}
          {jType==="guided"&&<div style={{marginBottom:14}}>{GUIDED[eType].map((q,i)=><div key={i} style={{marginBottom:12}}><div style={{fontSize:12,color:"#7a9a8a",marginBottom:5,lineHeight:1.5,fontWeight:600}}>{q}</div><textarea value={ga[q]||""} onChange={e=>setGa(a=>({...a,[q]:e.target.value}))} placeholder="Your answer..." rows={3} style={{width:"100%",padding:"10px 12px",borderRadius:10,fontSize:13,background:"#0d1f18",border:"1px solid #1a3028",color:"#fff",outline:"none",resize:"none",lineHeight:1.5,display:"block"}}/></div>)}</div>}
          <button onClick={saveJ} disabled={jType==="free"?!ft.trim():Object.values(ga).every(v=>!v?.trim())} style={{width:"100%",padding:"13px",borderRadius:12,border:"none",background:"#00FF87",color:"#001a0a",fontSize:14,fontWeight:900,cursor:"pointer",fontFamily:"'Space Mono',monospace",opacity:(jType==="free"?!ft.trim():Object.values(ga).every(v=>!v?.trim()))?0.4:1}}>Save Entry ✓</button>
          </div>}
        </div>}
        {tab==="profile"&&<div style={{paddingTop:14}}><div style={{...CARD,textAlign:"center",marginBottom:12}}><div style={{width:56,height:56,borderRadius:"50%",background:"#00FF8720",display:"flex",alignItems:"center",justifyContent:"center",fontSize:24,margin:"0 auto 8px"}}>👤</div><div style={{fontSize:15,fontWeight:700,color:"#fff"}}>My Stats</div></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:12}}>{[{label:"Total Points",value:pts,color:"#FBBF24",icon:"⭐"},{label:"Drills Done",value:doneD.length,color:"#00FF87",icon:"⚡"},{label:"Rope Rounds",value:ropeDone,color:"#34D399",icon:"🪢"},{label:"Journal Entries",value:journals.length,color:"#C084FC",icon:"📓"}].map((s,i)=><div key={i} style={{...CARD,textAlign:"center",marginBottom:0}}><div style={{fontSize:20,marginBottom:5}}>{s.icon}</div><div style={{fontSize:20,fontWeight:900,color:s.color}}>{s.value}</div><div style={{fontSize:11,color:"#4a7a5a"}}>{s.label}</div></div>)}</div>{dHistory.length>0&&<div style={CARD}><div style={{...L,marginBottom:10}}>RECENT ACTIVITY</div>{dHistory.slice(0,8).map((h,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",padding:"8px 0",borderBottom:i<Math.min(dHistory.length,8)-1?"1px solid #1a2820":"none"}}><span style={{fontSize:13,color:"#c8e8d8"}}>🎾 {h.drill}</span><span style={{fontSize:11,color:"#4a7a5a"}}>{h.date}</span></div>)}</div>}</div>}
      </div>
      {activeDrill&&<DrillModal drill={activeDrill} onClose={closeDrill}/>}
      <div style={{position:"fixed",bottom:0,left:"50%",transform:"translateX(-50%)",width:"100%",maxWidth:430,background:"#0a1a13",borderTop:"1px solid #1a2820",display:"flex",padding:"5px 0 16px",backdropFilter:"blur(20px)",zIndex:50}}>
        {TABS.map(t=><button key={t.id} onClick={()=>setTab(t.id)} style={{flex:1,display:"flex",flexDirection:"column",alignItems:"center",gap:2,background:"transparent",border:"none",cursor:"pointer",padding:"5px 0"}}><span style={{fontSize:17}}>{t.icon}</span><span style={{fontSize:8,fontWeight:700,letterSpacing:0.3,color:tab===t.id?"#00FF87":"#3a5a4a",fontFamily:"'Space Mono',monospace"}}>{t.label}</span></button>)}
      </div>
    </div>
  );
}
